export const GET_LIST_MOVIE = "GET_LIST_MOVIE"

export const GET_LIST_MOVIE_DANG_CHIEU = "GET_LIST_MOVIE_DANG_CHIEU"

export const GET_LIST_MOVIE_SAP_CHIEU = "GET_LIST_MOVIE_SAP_CHIEU"

export const GET_MOVIE_ID = "GET_MOVIE_ID"