export const LAY_DANH_SACH_PHONG_VE = "LAY_DANH_SACH_PHONG_VE";

export const QUAN_LY_GHE_DANG_DAT = "QUAN_LY_GHE_DANG_DAT";

export const DAT_VE_HOAN_TAT = "DAT_VE_HOAN_TAT";

export const CHUYEN_TAB_LICH_SU_DAT_VE = "CHUYEN_TAB_LICH_SU_DAT_VE";

export const CHUYEN_TAB__DAT_VE = "CHUYEN_TAB__DAT_VE";

export const QUAN_LY_GHE_DANG_DAT_SIGNALR = "QUAN_LY_GHE_DANG_DAT_SIGNALR";